name: Publish Package to release
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - run: npm i
      - run: npm run build

      - name: 创建 GitHub Release
        id: create_release_rmst
        uses: actions/create-release@latest
        env:
          # 配置github token  （这个无需去github配置，默认存在的）
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # 标签名
          tag_name: v${{ steps.version.outputs.value }}
          # release名
          release_name: v${{ steps.version.outputs.value }}

      - name: 上传 Release dist
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # 上传URL为创建GitHub Release步骤的输出值，可通过配置的id获取
          upload_url: ${{ steps.create_release_rmst.outputs.upload_url }}
          # 上传文件信息
          asset_path: ./dist
          asset_name: dist
          # asset_content_type: application/js
